#!/bin/sh
bspc rule -r "*"

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier lock
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true

bspc config normal_border_color "#ebdbb2"
bspc config focused_border_color "#257777"
bspc config border_width 2
bspc monitor -d 1 2 3 4 5
bspc config window_gap 25

$HOME/.config/polybar/launch.sh
